### ISSUE TITLE
readthedocs & switching to markdown source from reStructuredText

### ISSUE THREAD

**Issue by dhimmel** [greenelab/onboarding#2]
I'm planning on how to make the migration from rst to md.

Are we still using http://greenelab-onboarding.readthedocs.io/en/latest/? How/where is readthedocs configured?

I think we should be able to use markdown with readthedocs, see http://docs.readthedocs.io/en/latest/getting_started.html#in-markdown. However, I'm not sure RTD is actually desirable here:

+ the GitHub interface is fine for browsing rendered READMEs.
+ you lose the close connection to the source code
+ it adds complexity

**Comment by cgreene** [comment]
RTD is now built from github. I don't feel strongly about sticking with RTD if we move to markdown. The GitHub interface is fine. However, I would like things to all be in a single page with sections (currently it's a bunch of separate rst files) so we'd need to concatenate the markdown files. But, yea, this seems fine to me :)

**Comment by dhimmel** [comment]
@cgreene anyway to redirect the old RTD URL (http://greenelab-onboarding.readthedocs.io/en/latest/) to this repo (perhaps https://github.com/greenelab/onboarding/blob/master/onboarding.md).

**Comment by cgreene** [comment]
As hard as it is to believe... I think this issue is tracking that feature and it's still open:
https://github.com/rtfd/readthedocs.org/issues/1408

**Comment by dhimmel** [comment]
Oh wow! That's crazy. And I'm guessing it'd also be hard at this point to edit the RTD to say:

> The Greene Lab onboarding information [has moved](https://git.io/vbFO9).

**Comment by cgreene** [comment]
I didn't succeed, but I did delete that repo. We'll need to update links to that (thanks for snagging the labcarpentry one) 👍
